INSERT INTO films (id, name, description, year, genre_id, minimal_age, duration_in_minutes, file_id)
VALUES
(1, 'Oppenheimer',
 'World War II begins, and Oppenheimer is put in charge of the Manhattan Project. He has to create a nuclear bomb faster than the Third Reich can do so.',
 2023, 8, 18, 180, 1),
 (2, 'Evil Dead Rise',
 'Mother, possessed by dark forces, tries to kill her children. The nephews are protected by Aunt Beth - they have to survive until morning and fight off an army of the dead.',
 2023, 7, 18, 96, 2),
 (3, 'John Wick: Chapter 4',
 'The ambitious heroes are forced to fight against each other - because they have taken oaths and live by a code of assassins.',
 2023, 6, 18, 169, 3),
 (4, 'Guardians of the Galaxy Vol. 3',
 'James Gunn forever says goodbye to his favorite characters: after the third film, the composition of the superhero team almost completely changes.',
 2023, 3, 16, 150, 4),
 (5, 'Blackberry',
 'An atypical biographical drama about success. The protagonists launch the revolutionary Blackberry button phone and years later slowly lose the competition to Apple.',
 2023, 8, 16, 120, 5),
 (6, 'Dungeons & Dragons: Honor Amoung Thieves',
 'The adventurer Edgin and the barbarian Holga escape from prison. They want to find his daughter and bring his dead wife back to life with the help of a hidden artifact.',
 2023, 11, 12, 134, 6),
 (7, 'The Super Mario Bros. Movie',
 'Mario the plumber finds himself in the fantasy Mushroom Kingdom. And his brother Luigi is kidnapped by the minions of the turtle-like villain Bowser.',
 2023, 9, 6, 92, 7),
 (8, 'Spyder-Man: Across the Spyder-Verse',
 'Miles Morales combines two lives - an ordinary teenager and a superhero. At this time, a new villain, Blur, appears on the streets of Brooklyn.',
 2023, 3, 16, 140, 8),
(9, 'Barbie',
 'Barbie spends her days carefree in Barbieland: having fun with her friends, relaxing on the beach and sweet-talking Ken. One day, everything changes.',
 2023, 4, 18, 114, 9),
(10, 'The Covenant',
 'March 2018, Afghanistan. U.S. Army Sergeant John Kinley goes on a dangerous mission and is ambushed by the Taliban. He is miraculously rescued by local interpreter Ahmed.',
 2023, 5, 18, 123, 10);